spring.application.name=sheetService
server.port=9000
spring.data.mongodb.uri=mongodb+srv://dbUser:1234@clustersolorpg.d5uz3ft.mongodb.net/?retryWrites=true&w=majority&appName=ClusterSoloRPG
spring.data.mongodb.database=crudCharactersDB